### ISSUE TITLE
error: DisableFTZ needs an implentation

### ISSUE THREAD

**Issue by linuxcpp6** [KhronosGroup/SYCL-CTS#323] opened 2022-04-06 07:31 UTC
when build,error:

error: ForceFTZ needs an implentation

error: DisableFTZ needs an implentatio

nerror: RestoreFPState needs an implementation

Why is it?

**Comment by bader** [comment] 2022-07-20 15:31
@TechnologyAndEducation, sorry for the delay.
Could you provide the compiler version you use to build SYCL-CTS and what compiler options are used, please?
GitHub Actions CI builds SYCL-CTS using three different compilers and all tests build fine except the list from the corresponding filter - https://github.com/KhronosGroup/SYCL-CTS/tree/SYCL-2020/ci.

**Comment by gmlueck** [comment] 2023-12-14 17:02
Closing this for now because we can't reproduce it.  Please reopen if you want to discuss further.

**Closed by gmlueck** 2023-12-14 17:02 UTC
Labels: Agenda
